site_name: "slicer profiles"
site_url: "https://nanodize.github.io/slicer-profiles/"
site_author: "Nanodize"
site_description: "profiles for various slicers"
edit_uri: ""

copyright: Copyright &copy; 2021 Nanodize

repo_name: slicer-profiles
repo_url: https://github.com/Nanodize/slicer-profiles
version: 0.1.0

theme:
  language: en
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: amber
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.share
    - search.highlight

plugins:
  - search:
    lang: en

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: http://instagram.com/nanodize
    - icon: fontawesome/brands/github
      link: https://github.com/Nanodize
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nanodize
