site_name: "slicer profiles"
site_url: "https://nanodize.github.io/slicer-profiles/"
site_author: "Nanodize"
site_description: "profiles for various slicers"
edit_uri: ""

copyright: Copyright &copy; 2021 Nanodize

repo_name: slicer-profiles
repo_url: https://github.com/Nanodize/slicer-profiles
version: 0.1.0

theme:
  language: en
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: amber
      toggle:
        icon: material/eye
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.share
    - search.highlight

plugins:
  - search:
      lang: ru

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/nanodize
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/nanodize
    - icon: fontawesome/brands/discord
      link: https://discord.gg/CnSnHRc
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nanodize
    - icon: fontawesome/brands/github
      link: https://github.com/Nanodize
    - icon: fontawesome/brands/pinterest
      link: https://www.pinterest.de/nanodize

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
